name: Release

on:
  workflow_dispatch:
  push:
    tags: ['*']

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install environment
        run: npm ci

      - name: Prepare for release
        run: npm run prepare

      - name: Publish new version to NPM
        id: publish-to-npm
        run: |
          echo "publishing"
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

permissions:
  id-token: write